runtime: nodejs16 

env_variables:
  DB_INSTANCE_NAME: "gt3dproductsv01:us-east4:gt3dp-instance"
  DB_HOST: "34.86.87.232"
  DB_DATABASE: "gt3dp-db"
  DB_USER: "gt3dp-bhanu"
  DB_PASS: "Welcome@123"
  PORT: "8080"